spring:
  application:
    name: pirates-crew

  datasource:
    url: jdbc:postgresql://localhost:5432/pirates
    username: postgres
    password: 1997
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    filter:
      dispatcher-types: error, request

server:
  port: 8080
  servlet:
    context-path: /api/client

url:
  api: "https://api.api-onepiece.com/v2/"

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG



